version: '3.8'

services:
    web:
        build: 
            context: ./services/web
            dockerfile: Dockerfile.prod
        command: gunicorn --bind 0.0.0.0:5000 manage:app
        expose: 
            - 5000
        env_file:
            - ./.env.prod
        depends_on:
            - db
        volumes:
            - static_volume:/home/app/web/project/static
            - media_volume:/home/app/web/project/media
    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data_prod:/var/lib/postgresql/data
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./services/nginx
        ports:
            - 1107:80
        depends_on:
            - web
        volumes:
            - static_volume:/home/app/web/project/static
            - media_volume:/home/app/web/project/media

volumes:
    postgres_data_prod:
    static_volume:
    media_volume:
